### ISSUE TITLE
Setup Redux (+Redux-thunk) for persistence state management

### ISSUE THREAD

**Issue by benjaminkostiuk** [QueueTime/qtime-frontend#5]
Setup Redux and maybe Redux-thunk to manage persistent state management in the app

* Install redux
* Find a tutorial to setup the building blocks of the workflow.

## Definition of done
* Redux installed
* Redux-thunk installed if we need it
* Basic store and actions file setup in the app.

**Comment by benjaminkostiuk** [comment]
This might not be necessary since most global state falls under authentication and theme management, handled by React.context.

**Comment by dhruv423** [comment]
Added Recoil State Management for passing Location around the app
